CREATE TYPE "public"."resume_input_source" AS ENUM('user', 'linkedin', 'inferred');--> statement-breakpoint
CREATE TYPE "public"."resume_source" AS ENUM('manual', 'linkedin', 'import');--> statement-breakpoint
CREATE TYPE "public"."resume_status" AS ENUM('draft', 'ready', 'archived');--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resume_education" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"resumeId" uuid NOT NULL,
	"school" varchar(256) NOT NULL,
	"degree" varchar(128),
	"field" varchar(128),
	"startDate" date,
	"endDate" date,
	"gpa" varchar(32),
	"notes" text,
	"sortOrder" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resume_experience" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"resumeId" uuid NOT NULL,
	"roleTitle" varchar(256) NOT NULL,
	"company" varchar(256) NOT NULL,
	"location" varchar(128),
	"startDate" date,
	"endDate" date,
	"isCurrent" boolean DEFAULT false NOT NULL,
	"summary" text,
	"highlights" jsonb,
	"sortOrder" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resume_input" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"resumeId" uuid NOT NULL,
	"key" varchar(128) NOT NULL,
	"value" jsonb NOT NULL,
	"source" "resume_input_source" DEFAULT 'user' NOT NULL,
	"confidence" integer,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resume_link" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"resumeId" uuid NOT NULL,
	"label" varchar(128) NOT NULL,
	"url" varchar(512) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resume_profile" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"resumeId" uuid NOT NULL,
	"fullName" varchar(256) NOT NULL,
	"headline" varchar(256),
	"jobField" varchar(128),
	"email" varchar(256),
	"phone" varchar(64),
	"location" varchar(128),
	"website" varchar(256),
	"summary" text,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resume_skill" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"resumeId" uuid NOT NULL,
	"name" varchar(128) NOT NULL,
	"category" varchar(128),
	"proficiency" varchar(64),
	"sortOrder" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resume" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" varchar(255) NOT NULL,
	"title" varchar(256) DEFAULT 'Resume' NOT NULL,
	"status" "resume_status" DEFAULT 'draft' NOT NULL,
	"source" "resume_source" DEFAULT 'manual' NOT NULL,
	"rawLinkedIn" jsonb,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_post" ADD CONSTRAINT "pg-drizzle_post_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resume_education" ADD CONSTRAINT "pg-drizzle_resume_education_resumeId_pg-drizzle_resume_id_fk" FOREIGN KEY ("resumeId") REFERENCES "public"."pg-drizzle_resume"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resume_experience" ADD CONSTRAINT "pg-drizzle_resume_experience_resumeId_pg-drizzle_resume_id_fk" FOREIGN KEY ("resumeId") REFERENCES "public"."pg-drizzle_resume"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resume_input" ADD CONSTRAINT "pg-drizzle_resume_input_resumeId_pg-drizzle_resume_id_fk" FOREIGN KEY ("resumeId") REFERENCES "public"."pg-drizzle_resume"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resume_link" ADD CONSTRAINT "pg-drizzle_resume_link_resumeId_pg-drizzle_resume_id_fk" FOREIGN KEY ("resumeId") REFERENCES "public"."pg-drizzle_resume"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resume_profile" ADD CONSTRAINT "pg-drizzle_resume_profile_resumeId_pg-drizzle_resume_id_fk" FOREIGN KEY ("resumeId") REFERENCES "public"."pg-drizzle_resume"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resume_skill" ADD CONSTRAINT "pg-drizzle_resume_skill_resumeId_pg-drizzle_resume_id_fk" FOREIGN KEY ("resumeId") REFERENCES "public"."pg-drizzle_resume"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resume" ADD CONSTRAINT "pg-drizzle_resume_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "pg-drizzle_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "pg-drizzle_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "resume_education_resume_idx" ON "pg-drizzle_resume_education" USING btree ("resumeId");--> statement-breakpoint
CREATE INDEX "resume_education_sort_idx" ON "pg-drizzle_resume_education" USING btree ("sortOrder");--> statement-breakpoint
CREATE INDEX "resume_experience_resume_idx" ON "pg-drizzle_resume_experience" USING btree ("resumeId");--> statement-breakpoint
CREATE INDEX "resume_experience_sort_idx" ON "pg-drizzle_resume_experience" USING btree ("sortOrder");--> statement-breakpoint
CREATE INDEX "resume_input_resume_idx" ON "pg-drizzle_resume_input" USING btree ("resumeId");--> statement-breakpoint
CREATE INDEX "resume_input_key_idx" ON "pg-drizzle_resume_input" USING btree ("key");--> statement-breakpoint
CREATE INDEX "resume_link_resume_idx" ON "pg-drizzle_resume_link" USING btree ("resumeId");--> statement-breakpoint
CREATE INDEX "resume_link_label_idx" ON "pg-drizzle_resume_link" USING btree ("label");--> statement-breakpoint
CREATE INDEX "resume_profile_resume_idx" ON "pg-drizzle_resume_profile" USING btree ("resumeId");--> statement-breakpoint
CREATE UNIQUE INDEX "resume_profile_resume_unique" ON "pg-drizzle_resume_profile" USING btree ("resumeId");--> statement-breakpoint
CREATE INDEX "resume_skill_resume_idx" ON "pg-drizzle_resume_skill" USING btree ("resumeId");--> statement-breakpoint
CREATE INDEX "resume_skill_name_idx" ON "pg-drizzle_resume_skill" USING btree ("name");--> statement-breakpoint
CREATE INDEX "resume_user_idx" ON "pg-drizzle_resume" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "resume_status_idx" ON "pg-drizzle_resume" USING btree ("status");